@Reelkix.BackOffice.API_HostAddress = https://localhost:7037/api

POST {{Reelkix.BackOffice.API_HostAddress}}/products/
Content-Type: application/json
{
  "name": "GT Cut 1 'Grinch'",
  "description": "GT Cut 1 'Grinch'",
  "manufacturerId": "E7A5B1BB-D2DD-49DC-B4EB-EC80308CBA1F",
  "costPrice": 3800,
  "sellingPrice": 4388,
  "imageUrls": [
    "https://photo.yupoo.com/oxmade/1611a8a1/1b4ae000.jpg"
  ]
}
###

GET {{Reelkix.BackOffice.API_HostAddress}}/products/42D30297-000A-42D5-9305-61EDFCC04D82
Accept: application/json
###

GET {{Reelkix.BackOffice.API_HostAddress}}/products
Accept: application/json
###

GET {{Reelkix.BackOffice.API_HostAddress}}/manufacturers
Accept: application/json
###

GET {{Reelkix.BackOffice.API_HostAddress}}/manufacturers/E7A5B1BB-D2DD-49DC-B4EB-EC80308CBA1F
Accept: application/json
###

PUT {{Reelkix.BackOffice.API_HostAddress}}/manufacturers/E7A5B1BB-D2DD-49DC-B4EB-EC80308CBA1F
Content-Type: application/json
{
  "name": "OX",
  "description": "OX Batch"
}
###